export const FETCH_DOG_EVENTS = 'FETCH_DOG_EVENTS'
export const FETCH_CURRENT_DAY_DATA = 'FETCH_CURRENT_DAY_DATA'
export const UPDATE_SPECIFIC_FIELD_IN_STORE = 'UPDATE_SPECIFIC_FIELD_IN_STORE'

/* AUTH ACTIONS */
export const FETCH_DOG_NAME = 'FETCH_DOG_NAME'
export const SAVE_ARR_OF_DOGS_IN_STORE = 'SAVE_ARR_OF_DOGS_IN_STORE'
export const FETCH_ARR_OF_DOGS_FROM_DB_TO_ASYNCSTORAGE = 'FETCH_ARR_OF_DOGS_FROM_DB_TO_ASYNCSTORAGE'
export const SAVE_DOG_NAME_IN_STORE = 'SAVE_DOG_NAME_IN_STORE'
